### ISSUE TITLE
Some text strings are used in older Minecraft versions only

### ISSUE THREAD

**Issue by Greg-21** [thexaero/Better-PVP-Translations#15]
UPDATED TO REFLECT THE STATE FROM BETTER PVP VERSION 21.16.0 AND 21.10.6.

I tested multiple versions of your Better PvP mod, and found a few text strings that are exclusive to specific Minecraft versions. These text strings are listed an grouped below.

For every group, I will have a question. I would be grateful if you could answer these questions.

(1) Only used up to and including 1.16:
* `gui.xaero_render_layer` (line 273)

(2) Only used in 1.14 and newer:
* `gui.xaero_cross_tp` (line 276)

(3) Only used up to and including 1.12:
* `gui.xaero_box_cave_maps` (line 302)

(4) Only used up to and including 1.8:
* `gui.xaero_waypoints_scale` (line 163)
* `gui.xaero_box_waypoints_scale` (line 396)
* `gui.xaero_entity_radar` (line 224)
* `gui.xaero_entity_radar_type` (line 365)
* `gui.xaero_box_distance` (line 305)
* `gui.xaero_auto_clamp_depth` (line 389)
* `gui.xaero_waypoints_clamp_depth` (line 390)
* `gui.xaero_box_waypoints_clamp_depth` (line 393)
* `gui.xaero_box_waypoints_distance_scale` (line 394)
* `gui.xaero_box_waypoints_name_scale` (line 395)

Ad 1: Why it has been removed in 1.17? Do you plan to bring it back or it will stay that way from now on?
Ad 2:  It is probably impossible to backport due to Minecraft/Forge API limitations or simply not worth the effort, but I would like to make sure.
Ad 3: This is probably an oversight. In 1.12 the new text string that superseded this one should be used, as 1.12 has the new ceiling detection.
Ad 4: Versions 1.8 and 1.7 are currently stuck on an older mod version. Will this change in the future? What is your plan here?

**Comment by thexaero** [comment]
Thank you for the feedback!
1. It was removed because render layers don't exists in 1.17. Never existed on Fabric so the option did nothing and now Forge completely reworked their UI system.
2. You can't teleport to another dimension pre 1.14.
3. Didn't realize this was the case. Really appreciate it!
4. I'm only going to release bug fixes and update translations for 1.7 and 1.8, so these lines are necessary for that purpose. I might drop updating translations but haven't decided yet.

**Comment by Greg-21** [comment]
Thank you for the explanation. I have one more question, how long are you going to support 1.8 and 1.7? Any estimates?

**Comment by thexaero** [comment]
Sorry for not responding sooner. I'm not sure. Probably a long time.

**Comment by thexaero** [comment]
I think this is "resolved" now, so I'm closing the issue.
