### ISSUE TITLE
This mod cannot display Chinese normally in the setting interface.

### ISSUE THREAD

**Issue by rongke1997** [thexaero/Better-PVP-Translations#21]
Just like my title, I try to translate en_us.json in the lang folder and name it zh_cn.json, and then start the game,The minimap and worldmap settings interface is still in English .Can you take a look at this question ？

**Comment by Greg-21** [comment]
Works for me (and always did), so I have a few questions for you:
* what version of Minecraft are you trying to test your translation on?
* what is the exact name of the file containing your translation?
* what location in the file system do you put the file in?

**Comment by rongke1997** [comment]
Minecraft 1.17.1-，Xaeros_Minimap_21.22.6_Fabric_1.17.1，XaerosWorldMap_1.18.8_Fabric_1.17.1，
Before Translated document name is Xaeros_Minimap_21.22.6_Fabric_1.17.1.jar\assets\xaerobetterpvp\lang\en_us.json ,Translated file Xaeros_Minimap_21.22.6_Fabric_1.17.1.jar\assets\xaerobetterpvp\lang\ zh_cn.json. The file after adding my translation file :[https://github.com/rongke1997/MC-mod](https://github.com/rongke1997/MC-mod)

**Comment by Greg-21** [comment]
Thanks. I've found the source of your problems in logs, look:
```
[Render thread/WARN]: Skipped language file: xaerobetterpvp:lang/zh_cn.json (com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 473 column 3 path $.gui.xaero_settings_not_found)
[Render thread/WARN]: Skipped language file: xaeroworldmap:lang/zh_cn.json (com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 105 column 3 path $.gui.xaero_waypoint_backgrounds)
```

Basically, your translation files cause JSON parsing errors as they lack commas at the ends of the following lines: 472 (Better PvP mod), and 104 & 116 (Xaero's World Map).

In the future, when working with Minecraft translation files (and JSON files in general), you should pay more attention to such things. Your current translations have a lot of strange and redundant whitespace characters here and there.

**Comment by rongke1997** [comment]
Thank you very much, future translation documents must pay attention to these issues .

**Comment by thexaero** [comment]
@Greg-21 This is why I prefer the old lang format here :D

**Comment by Greg-21** [comment]
Xaero, it looks like you were right back in the day...
